---
- name: "elastic-product - Include Task 'download_product.yml'"
  include_tasks: download_product.yml
  tags:
    - download

- name: "elastic-product - Include Task 'unarchive_product.yml'"
  include_tasks: unarchive_product.yml
  tags:
    - unarchive

- name: "elastic-product - Include Task 'configure_product.yml'"
  include_tasks: configure_product.yml
  vars:
    template_file: "templates/{{ elastic_product }}.yml.j2"
  tags:
    - configure
