---
- name: "elastic_product - Install required package 'tar'"
  ansible.builtin.package:
    name: tar
    state: present

- name: "elastic_product - Create '{{ elastic_product_dest_dir }}' directory"
  ansible.builtin.file:
    name: "{{ elastic_product_dest_dir }}"
    state: directory
    owner: "{{ elastic_user }}"
    group: "{{ elastic_group }}"
    mode: '660'

- name: "elastic_product - Unarchive '{{ elastic_product_download_dir }}/{{ elastic_product_download_file }}' to '{{ elastic_product_dest_dir }}'"
  ansible.builtin.unarchive: 
    src: "{{ elastic_product_download_dir }}/{{ elastic_product_download_file }}"
    dest: "{{ elastic_product_dest_dir }}"
    owner: "{{ elastic_user }}"
    group: "{{ elastic_group }}"
    extra_opts:
      - "--strip-components=1"
