---
- name: "elastic - Install required package 'tar'"
  package:
    name: tar
    state: present

- name: "elastic - Create '{{ elastic_dest_dir }}' directory"
  file:
    name: "{{ elastic_dest_dir }}"
    state: directory
 
- name: "elastic - Unarchive '{{ elastic_download_dir }}/{{ elastic_download_file }}' to '{{ elastic_dest_dir }}'"
  unarchive: 
    src: "{{ elastic_download_dir }}/{{ elastic_download_file }}"
    dest: "{{ elastic_dest_dir }}"
    extra_opts:
      - "--strip-components=1"
